<?php 
$this->title = "Delete album";
$this->headTitle($this->title);
?>
<p>Are you sure that you want to delete 
  '<?php echo $this->escape($this->festivals['name']); ?>' by 
  '<?php echo $this->escape($this->festivals['edition']); ?>'?
</p>
<form action="<?php echo $this->url(array('action'=>'linkfestivalsdelete')); ?>" method="post">
<div>
  <input type="hidden" name="id" value="<?php echo $this->id; ?>" />
  <input type="hidden" name="id_festival" value="<?php echo $this->id_festival; ?>" />
  <input type="submit" name="del" value="Yes" />
  <input type="submit" name="del" value="No" />
</div>
</form>