<table class="table  table-striped">
<tr>
    <th>Nombre</th>
    <th>Ciudad</th>
    <th>Edición</th>
    <th>&nbsp;</th>
</tr>
<?php 
function UserHasThisFestival($festival,$data)
{
	foreach ($data as $pair):
		if (in_array($festival, $data)):
			return true;
			break;
		endif;
	endforeach;
	return false;
}
foreach($this->festivals as $festivals) : 
?>
<tr>
    <td><?php echo $this->escape($festivals->name);?></td>
    <td><?php echo $this->escape($festivals->location);?></td>
    <td><?php echo $this->escape($festivals->edition);?></td>
    <td>
    <?php //if ($this->controller->UserHasThisFestival($festival->id,$this->usershasfestivals)):?>
       <?php if (UserHasThisFestival($festivals->id,$this->usershasfestivals)): ?> 
		       <a href="<?php echo $this->url(array('controller'=>'judges', 
		            'action'=>'linkfestivalsdelete', 'id'=>$this->id_judge,'id_festival'=>$festivals->id),null,true);?>">
		       		Desactivar
		       </a> 
       <?php else: ?>
       		<a href="<?php echo $this->url(array('controller'=>'judges', 
		            'action'=>'linkfestivalsadd', 'id'=>$this->id_judge,'id_festival'=>$festivals->id),null,true);?>">
		       		Activar
		       </a> 
       <?php endif;?>    
    </td>
</tr>
<?php endforeach; ?>
</table>